---
- name: Ansible copy directory to the remote server
  copy:
    src: portal
    dest: /data

- name: Install Portal webserver docker container
  docker_container:
    name: portal
    image: nimmis/apache-php7
    state: started
    pull: true
    ports:
      - "9000:80"
    volumes:
      - /data/portal:/var/www/html:ro

- name: Wait 300 seconds for port 9200 to become open on the host, don't start checking for 5 seconds
  wait_for:
    host: "{{ hostvars[inventory_hostname].ansible_host }}"
    port: 9000
    delay: 5
    timeout: 300
  become: no
  delegate_to: localhost
