#### WAF edit entry ###
- name: WAF - Get login token
  uri:
    url: "{{ request_url }}/restapi/v3/login"
    method: POST
    body: '{"username":"{{ waf_username }}", "password":"{{ waf_password }}"}'
    body_format: json
    headers:
      Content-Type: "application/json"
  register: waf_token
