---
- file:
    path: /data/db
    state: directory
    mode: 0755

- name: DB
  docker_container:
    name: db
    image: mariadb
    state: started
    pull: true
    ports:
      - "3306:3306"
    env:
      MYSQL_ROOT_PASSWORD: "{{ action_user_pw }}"
    volumes:
     - /data/db:/var/lib/mysql

- name: Wait 300 seconds for port 9200 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 3306
    delay: 10

# Removes anonymous user account for localhost
- mysql_user:
    name: ''
    host: localhost
    state: absent

# Removes all anonymous user accounts
- mysql_user:
    name: ''
    host_all: yes
    state: absent

# Create database user with name 'bob' and password '12345' with all database privileges
- mysql_user:
    name: bob
    password: 12345
    priv: '*.*:ALL'
    state: present

- name: Create a new database with name 'bobdata'
  mysql_db:
    name: demo
    state: present

# Copy database dump file to remote host and restore it to database 'my_db'
- name: Copy database dump file
  copy:
    src: /data/Colors/data/colors.sql
    dest: /tmp

- name: Restore database
  mysql_db:
    name: demo
    state: import
    target: /tmp/colors.sql

- name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
  mysql_db:
    state: import
    name: all
    target: /tmp/{{ inventory_hostname }}.sql

