---
- name: Ansible copy directory to the remote server
  copy:
    src: portal
    dest: /data

- name: Portal
  docker_container:
    name: portal
    image: nimmis/apache-php7
    state: started
    pull: true
    ports:
      - "9200:80"
    volumes:
      - /data/portal:/var/www/html:ro

- name: Wait 300 seconds for port 9200 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 9200
    delay: 10
    timeout: 300
  become: no
  delegate_to: localhost
