---
#- name: setup Action User
#  user: generate_ssh_key=yes name={{action_user}} password={{action_user_pw | password_hash('sha512') }} shell=/bin/bash

- name: Wait 600 seconds for port 22 to become open on the host, don't start checking for 10 seconds
  wait_for:
    host: "{{ hostvars[inventory_hostname].ansible_host }}"
    port: 22
    delay: 10
    timeout: 600